<a href="https://colab.research.google.com/github/25wh1a05ac-pavani/week-1/blob/main/Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")
# 1.1 Create a 1D array named 'arr1_1' with numbers from 0 to 99 (inclusive) using arange.
# 1.2 Create a 3x3 array named 'arr1_2' filled with ones.
# 1.3 Create a 2x4 array named 'arr1_3' filled with the number 7.
# 1.4 Create a 5x5 array named 'arr1_4' with random integers between 10 and 50 (inclusive).

# Your code for Task 1 here:
# 1.1
arr1_1 = np.arange(100)

# 1.2
arr1_2 = np.ones((3, 3))

# 1.3
arr1_3 = np.full((2, 4), 7)

# 1.4
arr1_4 = np.random.randint(10, 51, size=(5, 5))

print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])


# Task 2: Indexing and Slicing with Arrays
print("\n--- Task 2: Indexing and Slicing with Arrays ---")
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])

# 2.1 Extract the element at row 2, column 3 (0-indexed). Store it in 'val2_1'.
# 2.2 Extract the first row. Store it in 'row2_2'.
# 2.3 Extract the last column. Store it in 'col2_3'.
# 2.4 Extract the sub-array consisting of rows 1 and 2, and columns 0 and 1. Store it in 'sub_arr2_4'.
# 2.5 Using boolean indexing, select all elements in 'data' that are greater than 100. Store them in 'filtered_elements2_5'.

# Your code for Task 2 here:
# 2.1
val2_1 = data[2, 3]

# 2.2
row2_2 = data[0]

# 2.3
col2_3 = data[:, -1]

# 2.4
sub_arr2_4 = data[1:3, 0:2]

# 2.5
filtered_elements2_5 = data[data > 100]


# Task 3: Conditional Operations
print("\n--- Task 3: Conditional Operations ---")
arr3_1 = np.random.randint(1, 21, size=(4, 5)) # Random 4x5 array with values 1 to 20

# 3.1 Create a new array 'arr3_2' where elements in 'arr3_1' less than 10 are replaced with 0,
#     and elements greater than or equal to 10 remain unchanged.
# 3.2 Count how many elements in 'arr3_1' are even. Store the count in 'even_count3_3'.

# Your code for Task 3 here:
# 3.1
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

# 3.2
even_count3_3 = np.sum(arr3_1 % 2 == 0)


# Task 4: Aggregation Functions
print("\n--- Task 4: Aggregation Functions ---")
arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])

# 4.1 Calculate the sum of all elements in 'arr4_1'. Store it in 'sum4_1'.
# 4.2 Calculate the mean of each column. Store it in 'mean_cols4_2'.
# 4.3 Find the maximum value in each row. Store it in 'max_rows4_3'.
# 4.4 Calculate the standard deviation of the entire array. Store it in 'std4_4'.

# Your code for Task 4 here:
# 4.1
sum4_1 = np.sum(arr4_1)

# 4.2
mean_cols4_2 = np.mean(arr4_1, axis=0)

# 4.3
max_rows4_3 = np.max(arr4_1, axis=1)

# 4.4
std4_4 = np.std(arr4_1)


# Task 5: Reshaping and Flattening
print("\n--- Task 5: Reshaping and Flattening ---")
arr5_1 = np.arange(24) # 1D array from 0 to 23

# 5.1 Reshape 'arr5_1' into a 4x6 2D array. Store it in 'reshaped_arr5_2'.
# 5.2 Reshape 'arr5_1' into a 2x3x4 3D array. Store it in 'reshaped_arr5_3'.
# 5.3 Flatten 'reshaped_arr5_2' back into a 1D array. Store it in 'flattened_arr5_4'.
#     Use both `.ravel()` and `.flatten()` to see if there's a difference (though not visible in output).

# Your code for Task 5 here:

# 5.1
reshaped_arr5_2 = arr5_1.reshape(4, 6)

# 5.2
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

# 5.3
flattened_arr5_4 = reshaped_arr5_2.ravel()

# Using flatten() as well
flattened_copy5 = reshaped_arr5_2.flatten()

# Task 6: Broadcasting
print("\n--- Task 6: Broadcasting ---")
arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
scalar = 10
vector = np.array([100, 200, 300])

# 6.1 Add the 'scalar' to every element of 'arr6_1'. Store it in 'result6_1'.
# 6.2 Add the 'vector' to each row of 'arr6_1'. Store it in 'result6_2'.

# Your code for Task 6 here:
# 6.1
result6_1 = arr6_1 + scalar

# 6.2
result6_2 = arr6_1 + vector


# Task 7: Copying vs. Viewing Arrays
print("\n--- Task 7: Copying vs. Viewing Arrays ---")
original_arr7 = np.array([1, 2, 3, 4, 5])

# 7.1 Create a 'view' of 'original_arr7' named 'view_arr7' by slicing the entire array.
#     Modify the first element of 'view_arr7' to 99.
#     Observe how 'original_arr7' changes.
# 7.2 Create a 'copy' of 'original_arr7' named 'copy_arr7' using `.copy()`.
#     Modify the last element of 'copy_arr7' to 0.
#     Observe how 'original_arr7' remains unchanged.

# Your code for Task 7 here:

# 7.1
view_arr7 = original_arr7[:]
view_arr7[0] = 99

# 7.2
copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0

# Task 8: Stacking and Splitting Arrays
print("\n--- Task 8: Stacking and Splitting Arrays ---")
arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])

# 8.1 Vertically stack 'arr8_a' and 'arr8_b'. Store it in 'vstack_arr8_1'.
# 8.2 Horizontally stack 'arr8_a' and 'arr8_b'. Store it in 'hstack_arr8_2'.
# 8.3 Vertically stack 'vstack_arr8_1' and 'arr8_c'. Store it in 'combined_arr8_3'.
# 8.4 Split 'combined_arr8_3' into 3 equal parts (rows). Store them in 'part1', 'part2', 'part3'.

# Your code for Task 8 here:

# 8.1
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))

# 8.2
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))

# 8.3
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

# 8.4
part1, part2, part3 = np.vsplit(combined_arr8_3, [2, 4])

# Task 9: Sorting and Searching
print("\n--- Task 9: Sorting and Searching ---")
arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])

# 9.1 Sort 'arr9_1' in ascending order. Store it in 'sorted_arr9_1'.
# 9.2 Sort 'arr9_2d' along columns (i.e., each column sorted independently). Store it in 'sorted_cols9_2'.
# 9.3 Find the indices where the value 9 is present in 'arr9_1'. Store it in 'idx9_3'. (Hint: use np.where)
# 9.4 Find the index of the maximum value in 'arr9_1'. Store it in 'max_idx9_4'.

# Your code for Task 9 here:

# 9.1
sorted_arr9_1 = np.sort(arr9_1)

# 9.2
sorted_cols9_2 = np.sort(arr9_2d, axis=0)

# 9.3
idx9_3 = np.where(arr9_1 == 9)

# 9.4
max_idx9_4 = np.argmax(arr9_1)

--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[38 40 22 40 39]
 [24 43 14 12 49]]

--- Task 2: Indexing and Slicing with Arrays ---

--- Task 3: Conditional Operations ---

--- Task 4: Aggregation Functions ---

--- Task 5: Reshaping and Flattening ---

--- Task 6: Broadcasting ---

--- Task 7: Copying vs. Viewing Arrays ---

--- Task 8: Stacking and Splitting Arrays ---

--- Task 9: Sorting and Searching ---


In [3]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")
# 1.1 Create a Pandas Series named 's1_1' from a list of numbers [10, 20, 30, 40, 50].
# 1.2 Create a 3x4 NumPy array named 'np_array1_2' with random integers between 1 and 100.
# 1.3 Convert 'np_array1_2' into a Pandas DataFrame named 'df1_3' with columns 'A', 'B', 'C', 'D'.

# Your code for Task 1 here:


# 1.1 Create a Pandas Series
s1_1 = pd.Series([10, 20, 30, 40, 50])

# 1.2 Create a 3x4 NumPy array
np_array1_2 = np.random.randint(1, 101, size=(3, 4))

# 1.3 Convert NumPy array to DataFrame
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

print(s1_1)
print(np_array1_2)
print(df1_3)
# Task 2: Synthetic Data Generation for Practice
print("\n--- Task 2: Synthetic Data Generation for Practice ---")
# Create a DataFrame named 'df_sales' with 100 rows and the following columns:
# - 'Date': A range of dates from '2023-01-01' to '2023-04-09' (inclusive).
# - 'Region': Randomly chosen from ['East', 'West', 'North', 'South'].
# - 'Product': Randomly chosen from ['Laptop', 'Mouse', 'Keyboard', 'Monitor'].
# - 'Sales': Random integers between 100 and 1000.
# - 'Quantity': Random integers between 1 and 10.
# - Introduce 5 random NaN values in the 'Sales' column and 3 random NaN values in the 'Quantity' column.

# Your code for Task 2 here:

# Create DataFrame
df_sales = pd.DataFrame({
    'Date': pd.date_range('2023-01-01', periods=100),
    'Region': np.random.choice(['East', 'West', 'North', 'South'], 100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], 100),
    'Sales': np.random.randint(100, 1001, 100),
    'Quantity': np.random.randint(1, 11, 100)
})

# Introduce 5 NaN values in Sales
sales_nan = np.random.choice(df_sales.index, 5, replace=False)
df_sales.loc[sales_nan, 'Sales'] = np.nan

# Introduce 3 NaN values in Quantity
quantity_nan = np.random.choice(df_sales.index, 3, replace=False)
df_sales.loc[quantity_nan, 'Quantity'] = np.nan

print(df_sales.head())
# Introduce NaN values



# Task 3: Indexing and Slicing in DataFrames
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")
# Use 'df_sales' from Task 2.
# 3.1 Select only the 'Region' and 'Sales' columns. Store it in 'df3_1'.
# 3.2 Select rows where 'Product' is 'Laptop'. Store it in 'df3_2'.
# 3.3 Select rows where 'Region' is 'East' AND 'Sales' are greater than 500. Store it in 'df3_3'.
# 3.4 Select the 'Sales' value for the first entry where 'Product' is 'Monitor' (use .loc and .iloc). Store it in 'val3_4'.

# Your code for Task 3 here:

# 3.1 Select Region and Sales columns
df3_1 = df_sales[['Region', 'Sales']]

# 3.2 Rows where Product is Laptop
df3_2 = df_sales[df_sales['Product'] == 'Laptop']

# 3.3 Region is East and Sales > 500
df3_3 = df_sales[(df_sales['Region'] == 'East') & (df_sales['Sales'] > 500)]

# 3.4 Sales value for first Monitor
val3_4 = df_sales.loc[df_sales['Product'] == 'Monitor', 'Sales'].iloc[0]

print(df3_1.head())
print(df3_2.head())
print(df3_3.head())
print(val3_4)

# Task 4: Data Cleaning (Handling Missing Values)
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")
# Use 'df_sales' from Task 2 (which should have NaNs).
# 4.1 Check how many missing values are in each column. Store the result in 'missing_counts4_1'.
# 4.2 Fill missing 'Sales' values with the mean of the 'Sales' column. Store the modified DataFrame in 'df4_2_filled'.
# 4.3 Drop rows that have any missing values in 'df_sales'. Store the result in 'df4_3_dropped'.

# Your code for Task 4 here:
# 4.1 Count missing values
missing_counts4_1 = df_sales.isnull().sum()

# 4.2 Fill missing Sales with mean
df4_2_filled = df_sales.copy()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(df4_2_filled['Sales'].mean())

# 4.3 Drop rows with any missing values
df4_3_dropped = df_sales.dropna()

print(missing_counts4_1)
print(df4_2_filled.head())
print(df4_3_dropped.head())


# Task 5: Data Manipulation (Columns, Sorting, Grouping)
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")
# Use 'df_sales' (the original one with NaNs)
# 5.1 Create a new column 'Total_Revenue' which is 'Sales' * 'Quantity'.
#     (Be mindful of NaNs, the result should also be NaN where either Sales or Quantity is NaN).
# 5.2 Sort 'df_sales' by 'Date' in ascending order, then by 'Sales' in descending order. Store it in 'df5_2_sorted'.
# 5.3 Group 'df_sales' by 'Region' and calculate the sum of 'Sales' and 'Quantity' for each region.
#     Store the result in 'df5_3_grouped_region'.
# 5.4 Group 'df_sales' by 'Product' and find the average 'Sales' for each product.
#     Store the result in 'df5_4_grouped_product'.

# Your code for Task 5 here:
# 5.1 Create Total_Revenue column
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']

# 5.2 Sort by Date ascending and Sales descending
df5_2_sorted = df_sales.sort_values(by=['Date', 'Sales'], ascending=[True, False])

# 5.3 Group by Region and sum Sales & Quantity
df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()

# 5.4 Group by Product and average Sales
df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

print(df_sales.head())
print(df5_2_sorted.head())
print(df5_3_grouped_region)
print(df5_4_grouped_product)


--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---
0    10
1    20
2    30
3    40
4    50
dtype: int64
[[57  2 75 80]
 [56 48  7 66]
 [45 91 83 30]]
    A   B   C   D
0  57   2  75  80
1  56  48   7  66
2  45  91  83  30

--- Task 2: Synthetic Data Generation for Practice ---
        Date Region   Product  Sales  Quantity
0 2023-01-01   East  Keyboard  748.0       1.0
1 2023-01-02  North    Laptop  298.0       8.0
2 2023-01-03   West     Mouse  358.0       1.0
3 2023-01-04  South     Mouse  663.0       NaN
4 2023-01-05  North     Mouse  314.0       7.0

--- Task 3: Indexing and Slicing in DataFrames ---
  Region  Sales
0   East  748.0
1  North  298.0
2   West  358.0
3  South  663.0
4  North  314.0
         Date Region Product  Sales  Quantity
1  2023-01-02  North  Laptop  298.0       8.0
6  2023-01-07  North  Laptop  969.0      10.

In [4]:
import numpy as np
arr1 = np.arange(0, 10, 2)
print("Array using arange:", arr1)


Array using arange: [0 2 4 6 8]


In [30]:
arr2 = np.linspace(0, 1, 5)
print("Array using linspace:", arr2)


Array using linspace: [0.   0.25 0.5  0.75 1.  ]


In [31]:
arr3 = np.arange(1, 10).reshape((3, 3))
print("Reshaped Array (3x3):\n", arr3)

# flatten(): Convert multi-dimensional array to 1D
print("Flattened version:", arr3.flatten())

Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened version: [1 2 3 4 5 6 7 8 9]


In [24]:
data = np.array([[5, 8, 9], [2, 4, 6]])

print("Original Data:\n", data)

Original Data:
 [[5 8 9]
 [2 4 6]]


In [23]:
print("Sum of all elements:", np.sum(data))
print("Column-wise sum:", np.sum(data, axis=0))
print("Row-wise mean:", np.mean(data, axis=1))
print("Max value:", np.max(data))

Sum of all elements: 1360
Column-wise sum: [280 320 360 400]
Row-wise mean: [ 25.  65. 105. 145.]
Max value: 160


In [6]:
print("Index of max value (flattened):", np.argmax(data))
print("Min value:", np.min(data))
print("Standard Deviation:", np.std(data))

Index of max value (flattened): 15
Min value: 10
Standard Deviation: 46.09772228646444


In [22]:
a = np.array([3, 1, 7, 2, 9])
print("Original Array:", a)

Original Array: [3 1 7 2 9]


In [26]:
sorted_array = np.sort(a)
print("Sorted Array:", sorted_array)

# Find indices where condition is True (value > 4)
idx = np.where(a > 4)
print("Indices where value > 4:", idx)
print("Values > 4:", a[idx])

Sorted Array: [1 2 3 7 9]
Indices where value > 4: (array([2, 4]),)
Values > 4: [7 9]


In [7]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])

print("Matrix A:\n", A)
print("Vector B:", B)


Matrix A:
 [[1 2]
 [3 4]]
Vector B: [10 20]


In [8]:
C = A + B
print("Broadcasted Addition Result:\n", C)

Broadcasted Addition Result:
 [[11 22]
 [13 24]]


In [20]:
nums = np.array([1, 2, 3, 4, 5])

# Create boolean mask for condition nums > 3
mask = nums > 3
print("Mask (nums > 3):", mask)

Mask (nums > 3): [False False False  True  True]


In [27]:
filtered = nums[mask]
print("Filtered values:", filtered)

# np.where: apply conditional logic
result = np.where(nums % 2 == 0, "Even", "Odd")
print("Even or Odd:", result)

Filtered values: [4 5]
Even or Odd: ['Odd' 'Even' 'Odd' 'Even' 'Odd']


In [18]:
arr_orig = np.array([10, 20, 30])

# Creating a view (shares memory)
arr_view = arr_orig[:]
arr_view[0] = 99  # This change affects original
print("Original After View Change:", arr_orig)



Original After View Change: [99 20 30]


In [28]:
arr_copy = arr_orig.copy()
arr_copy[0] = 55  # This does NOT affect original
print("Original After Copy Change:", arr_orig)
print("Copy:", arr_copy)

Original After Copy Change: [99 20 30]
Copy: [55 20 30]


In [16]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Vertical stack (as rows)
v_stack = np.vstack((x, y))
print("Vertical Stack:\n", v_stack)


Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [33]:
h_stack = np.hstack((x, y))
print("Horizontal Stack:\n", h_stack)

# Split an array into 3 sub-arrays
z = np.arange(10)
split_arr = np.array_split(z, 3)
print("Split into 3 parts:", split_arr)

Horizontal Stack:
 [1 2 3 4 5 6]
Split into 3 parts: [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [9]:
rand_ints = np.random.randint(0, 100, size=(3, 3))
print("Random Integers:\n", rand_ints)

# Random values from standard normal distribution (mean=0, std=1)
rand_norm = np.random.randn(2, 4)
print("Random Normal Distribution:\n", rand_norm)


Random Integers:
 [[14 46 55]
 [11 62 70]
 [30 84 31]]
Random Normal Distribution:
 [[ 2.04390649  0.56344141 -0.2688966  -0.08467931]
 [ 0.08357265 -1.34542378  3.41872063  0.14262402]]


In [14]:
choices = np.random.choice([1, 3, 5, 7], size=5)
print("Random Choices:", choices)

# Setting a seed ensures reproducible random results
np.random.seed(42)
print("Seeded Random Number:", np.random.rand())

Random Choices: [7 1 3 1 5]
Seeded Random Number: 0.3745401188473625


In [12]:
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original 1D Array:", arr)

# Access single elements by index
print("Element at index 0:", arr[0])
print("Element at last index:", arr[-1])


Original 1D Array: [10 20 30 40 50 60]
Element at index 0: 10
Element at last index: 60


In [13]:
# Slice elements [start:stop] (stop is exclusive)
print("Slice from index 1 to 4:", arr[1:4])  # [20, 30, 40]

# Slice with step
print("Every second element:", arr[::2])     # [10, 30, 50]

# Reverse array
print("Reversed array:", arr[::-1])

Slice from index 1 to 4: [20 30 40]
Every second element: [10 30 50]
Reversed array: [60 50 40 30 20 10]


In [11]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:\n", matrix)

# Access element at row 1, column 2
print("Element at (1,2):", matrix[1, 2])  # 6

# Get entire first row
print("First row:", matrix[0, :])  # [1, 2, 3]

# Get entire second column
print("Second column:", matrix[:, 1])  # [2, 5, 8]

# Slice sub-matrix (top-left 2x2 block)
print("Top-left 2x2 block:\n", matrix[:2, :2])

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1,2): 6
First row: [1 2 3]
Second column: [2 5 8]
Top-left 2x2 block:
 [[1 2]
 [4 5]]


In [10]:
arr = np.array([5, 10, 15, 20, 25, 30])

# Create a boolean mask for values > 15
mask = arr > 15
print("Boolean Mask:", mask)

# Use mask to filter elements
print("Values greater than 15:", arr[mask])  # [20, 25, 30]

# Combine conditions
print("Even numbers > 10:", arr[(arr > 10) & (arr % 2 == 0)])

Boolean Mask: [False False False  True  True  True]
Values greater than 15: [20 25 30]
Even numbers > 10: [20 30]
